// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidtermExam;

namespace MidtermExam.Migrations
{
    [DbContext(typeof(BloggingDbContext))]
    [Migration("20201111103301_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MidtermExam.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 2,
                            StudentName = "Rakanishu"
                        },
                        new
                        {
                            StudentId = 3,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 4,
                            StudentName = "Archil"
                        },
                        new
                        {
                            StudentId = 5,
                            StudentName = "Rakanishu"
                        },
                        new
                        {
                            StudentId = 6,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 7,
                            StudentName = "Malxaz"
                        },
                        new
                        {
                            StudentId = 8,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 9,
                            StudentName = "Vaxtang"
                        },
                        new
                        {
                            StudentId = 10,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 11,
                            StudentName = "Vaxtang"
                        },
                        new
                        {
                            StudentId = 12,
                            StudentName = "Archil"
                        },
                        new
                        {
                            StudentId = 13,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 14,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 15,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 16,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 17,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 18,
                            StudentName = "Malxaz"
                        },
                        new
                        {
                            StudentId = 19,
                            StudentName = "Rakanishu"
                        },
                        new
                        {
                            StudentId = 20,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 21,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 22,
                            StudentName = "Rakanishu"
                        },
                        new
                        {
                            StudentId = 23,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 24,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 25,
                            StudentName = "Malxaz"
                        },
                        new
                        {
                            StudentId = 26,
                            StudentName = "Archil"
                        },
                        new
                        {
                            StudentId = 27,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 28,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 29,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 30,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 31,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 32,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 33,
                            StudentName = "Vaxtang"
                        },
                        new
                        {
                            StudentId = 34,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 35,
                            StudentName = "Vaxtang"
                        },
                        new
                        {
                            StudentId = 36,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 37,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 38,
                            StudentName = "Ana"
                        },
                        new
                        {
                            StudentId = 39,
                            StudentName = "Eka"
                        },
                        new
                        {
                            StudentId = 40,
                            StudentName = "Archil"
                        },
                        new
                        {
                            StudentId = 41,
                            StudentName = "Malxaz"
                        },
                        new
                        {
                            StudentId = 42,
                            StudentName = "Archil"
                        },
                        new
                        {
                            StudentId = 43,
                            StudentName = "Malxaz"
                        },
                        new
                        {
                            StudentId = 44,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 45,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 46,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 47,
                            StudentName = "Nikoloz"
                        },
                        new
                        {
                            StudentId = 48,
                            StudentName = "Mari"
                        },
                        new
                        {
                            StudentId = 49,
                            StudentName = "Giorgi"
                        },
                        new
                        {
                            StudentId = 50,
                            StudentName = "Archil"
                        });
                });

            modelBuilder.Entity("MidtermExam.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            SubjectName = "Operating Systems"
                        },
                        new
                        {
                            SubjectId = 2,
                            SubjectName = "Security"
                        },
                        new
                        {
                            SubjectId = 3,
                            SubjectName = "Databases"
                        },
                        new
                        {
                            SubjectId = 4,
                            SubjectName = ".NET"
                        },
                        new
                        {
                            SubjectId = 5,
                            SubjectName = "Web"
                        });
                });

            modelBuilder.Entity("MidtermExam.SubjectStudent", b =>
                {
                    b.Property<int>("SubjectStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Point")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("SubjectStudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectStudents");

                    b.HasData(
                        new
                        {
                            SubjectStudentId = 1,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 2,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 3,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 4,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 5,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 6,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 7,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 8,
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 9,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 10,
                            StudentId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 11,
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 12,
                            StudentId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 13,
                            StudentId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 14,
                            StudentId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 15,
                            StudentId = 8,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 16,
                            StudentId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 17,
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 18,
                            StudentId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 19,
                            StudentId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 20,
                            StudentId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 21,
                            StudentId = 11,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 22,
                            StudentId = 11,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 23,
                            StudentId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 24,
                            StudentId = 12,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 25,
                            StudentId = 13,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 26,
                            StudentId = 13,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 27,
                            StudentId = 14,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 28,
                            StudentId = 14,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 29,
                            StudentId = 15,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 30,
                            StudentId = 15,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 31,
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 32,
                            StudentId = 16,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 33,
                            StudentId = 17,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 34,
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 35,
                            StudentId = 18,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 36,
                            StudentId = 18,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 37,
                            StudentId = 19,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 38,
                            StudentId = 19,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 39,
                            StudentId = 20,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 40,
                            StudentId = 20,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 41,
                            StudentId = 21,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 42,
                            StudentId = 21,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 43,
                            StudentId = 22,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 44,
                            StudentId = 22,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 45,
                            StudentId = 23,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 46,
                            StudentId = 23,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 47,
                            StudentId = 24,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 48,
                            StudentId = 24,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 49,
                            StudentId = 25,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 50,
                            StudentId = 25,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 51,
                            StudentId = 26,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 52,
                            StudentId = 26,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 53,
                            StudentId = 27,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 54,
                            StudentId = 27,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 55,
                            StudentId = 28,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 56,
                            StudentId = 28,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 57,
                            StudentId = 29,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 58,
                            StudentId = 29,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 59,
                            StudentId = 30,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 60,
                            StudentId = 30,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 61,
                            StudentId = 31,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 62,
                            StudentId = 31,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 63,
                            StudentId = 32,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 64,
                            StudentId = 32,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 65,
                            StudentId = 33,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 66,
                            StudentId = 33,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 67,
                            StudentId = 34,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 68,
                            StudentId = 34,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 69,
                            StudentId = 35,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 70,
                            StudentId = 35,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 71,
                            StudentId = 36,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 72,
                            StudentId = 36,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 73,
                            StudentId = 37,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 74,
                            StudentId = 37,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 75,
                            StudentId = 38,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 76,
                            StudentId = 38,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 77,
                            StudentId = 39,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 78,
                            StudentId = 39,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 79,
                            StudentId = 40,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 80,
                            StudentId = 40,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 81,
                            StudentId = 41,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 82,
                            StudentId = 41,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 83,
                            StudentId = 42,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 84,
                            StudentId = 42,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 85,
                            StudentId = 43,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 86,
                            StudentId = 43,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 87,
                            StudentId = 44,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 88,
                            StudentId = 44,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 89,
                            StudentId = 45,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 90,
                            StudentId = 45,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 91,
                            StudentId = 46,
                            SubjectId = 4
                        },
                        new
                        {
                            SubjectStudentId = 92,
                            StudentId = 46,
                            SubjectId = 5
                        },
                        new
                        {
                            SubjectStudentId = 93,
                            StudentId = 47,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 94,
                            StudentId = 47,
                            SubjectId = 2
                        },
                        new
                        {
                            SubjectStudentId = 95,
                            StudentId = 48,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 96,
                            StudentId = 48,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 97,
                            StudentId = 49,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 98,
                            StudentId = 49,
                            SubjectId = 1
                        },
                        new
                        {
                            SubjectStudentId = 99,
                            StudentId = 50,
                            SubjectId = 3
                        },
                        new
                        {
                            SubjectStudentId = 100,
                            StudentId = 50,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("MidtermExam.SubjectStudent", b =>
                {
                    b.HasOne("MidtermExam.Student", null)
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MidtermExam.Subject", null)
                        .WithMany("Students")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
